name: Deploy Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8}
  HOST_PROD: ${{ secrets.HOST_PROD }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login registry.digitalocean.com -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet
        run: |
          sshpass -p "${PASSWORD_PROD}" ssh -o StrictHostKeyChecking=no ${USERNAME}@${HOST_PROD} << EOF
            docker pull ${IMAGE_NAME}
            docker stop laravel_app || true
            docker rm laravel_app || true
            docker run -d --name laravel_app -p 80:80 ${IMAGE_NAME}
          EOF
