name: new deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t registry.digitalocean.com/hatchcontainer/app:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push registry.digitalocean.com/hatchcontainer/app:${{ github.sha }}

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD_PROD }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            docker pull registry.digitalocean.com/hatchcontainer/app:${{ github.sha }}
            docker stop hatchcontainer || true
            docker rm hatchcontainer || true
            docker run -d --name hatchcontainer -p 80:80 registry.digitalocean.com/hatchcontainer/app:${{ github.sha }}

