name: Deploy Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login registry.digitalocean.com -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8}
          docker push registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8}

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet
        env:
          DOCKER_IMAGE: registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8}
          HOST_PROD: ${{ secrets.HOST_PROD }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
        run: |
          sshpass -p ${{ secrets.PASSWORD_PROD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_PROD }} << 'EOF'
            docker pull $DOCKER_IMAGE
            docker stop laravel_app || true
            docker rm laravel_app || true
            docker run -d --name laravel_app -p 80:80 $DOCKER_IMAGE
          EOF
