name: Deploy Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login registry.digitalocean.com -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8}
          docker push registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8}

      - name: Deploy to DigitalOcean Droplet (if needed)
        run: |
          # Aquí puedes añadir comandos para desplegar la imagen en un Droplet si es necesario
          # Por ejemplo:
          # ssh user@droplet_ip "docker pull registry.digitalocean.com/hatchcontainer/app:${GITHUB_SHA::8} && docker-compose up -d"
        if: false   #Descomenta esta línea y ajusta según tus necesidades

